// <auto-generated />
using System;
using AbleEaseInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbleEaseInfrastructure.Migrations
{
    [DbContext(typeof(AbleEaseDbContext))]
    partial class AbleEaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbleEaseDomain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("ProgramOrganizationSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ProgramOrganizationSSN", "ProgramId", "Id");

                    b.HasIndex("ProgramOrganizationSSN", "ProgramId")
                        .IsUnique();

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.AssessmentPatient", b =>
                {
                    b.Property<Guid>("AssessmentProgramOrganizationSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssessmentProgramId")
                        .HasColumnType("int");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<Guid>("PatientSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.HasKey("AssessmentProgramOrganizationSSN", "AssessmentProgramId", "AssessmentId", "PatientSSN");

                    b.HasIndex("PatientSSN");

                    b.ToTable("AssessmentPatients");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Disability", b =>
                {
                    b.Property<Guid>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN");

                    b.ToTable("Disabilities");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.FinancialAid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("percentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationSSN");

                    b.HasIndex("PatientSSN");

                    b.ToTable("FinancialAids");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.MedicalInfo", b =>
                {
                    b.Property<Guid>("PatientSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelativeSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TherapyDeatils")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientSSN", "Id");

                    b.HasIndex("RelativeSSN");

                    b.ToTable("MedicalInfos");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.PatientDisability", b =>
                {
                    b.Property<Guid>("PatientSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DisabilityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientSSN", "DisabilityID");

                    b.HasIndex("DisabilityID");

                    b.ToTable("PatientDisabilities");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.PatientWorksAtOrganization", b =>
                {
                    b.Property<Guid>("PatientSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("jobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientSSN");

                    b.HasIndex("OrganizationSSN");

                    b.ToTable("PatientWorksAtOrganizations");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FinancialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<string>("approvalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FinancialId")
                        .IsUnique()
                        .HasFilter("[FinancialId] IS NOT NULL");

                    b.HasIndex("PatientSSN");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.PhysicalTherapy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CenterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Doctorname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PatientSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("therapyDetails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CenterID");

                    b.HasIndex("PatientSSN");

                    b.ToTable("PhysicalTherapies");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.PhysiotherapyCenter", b =>
                {
                    b.Property<Guid>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN");

                    b.ToTable("PhysiotherapyCenters");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Program", b =>
                {
                    b.Property<Guid>("OrganizationSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrganizationSSN", "Id");

                    b.HasIndex("status");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.ReceivedMessages", b =>
                {
                    b.Property<Guid>("SenderSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceivedSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SenderSSN", "Id", "ReceivedSSN");

                    b.HasIndex("ReceivedSSN");

                    b.HasIndex("SentDate");

                    b.ToTable("ReceivedMessages");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaregiverSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PatientSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProgramOrganizationSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverSSN");

                    b.HasIndex("PatientSSN");

                    b.HasIndex("ProgramOrganizationSSN", "ProgramId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.SentMessages", b =>
                {
                    b.Property<Guid>("SenderSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceiverSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SenderSSN", "Id", "ReceiverSSN");

                    b.HasIndex("SentDate");

                    b.ToTable("SentMessages");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.User", b =>
                {
                    b.Property<Guid>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AbleEaseInfrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Caregiver", b =>
                {
                    b.HasBaseType("AbleEaseDomain.Entities.User");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationSSN")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("OrganizationSSN");

                    b.ToTable("Caregivers");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Organization", b =>
                {
                    b.HasBaseType("AbleEaseDomain.Entities.User");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Patient", b =>
                {
                    b.HasBaseType("AbleEaseDomain.Entities.User");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CaregiverSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProgramOrganizationSSN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelativeSSN")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CaregiverSSN");

                    b.HasIndex("RelativeSSN")
                        .IsUnique()
                        .HasFilter("[RelativeSSN] IS NOT NULL");

                    b.HasIndex("ProgramOrganizationSSN", "ProgramId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Relative", b =>
                {
                    b.HasBaseType("AbleEaseDomain.Entities.User");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Relatives");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Assessment", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Program", "program")
                        .WithOne("Assessment")
                        .HasForeignKey("AbleEaseDomain.Entities.Assessment", "ProgramOrganizationSSN", "ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("program");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.AssessmentPatient", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Patient", "patient")
                        .WithMany("assessmentPatients")
                        .HasForeignKey("PatientSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbleEaseDomain.Entities.Assessment", "Assessment")
                        .WithMany("assessmentPatients")
                        .HasForeignKey("AssessmentProgramOrganizationSSN", "AssessmentProgramId", "AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.FinancialAid", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Organization", "organization")
                        .WithMany("financialAids")
                        .HasForeignKey("OrganizationSSN")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AbleEaseDomain.Entities.Patient", "patient")
                        .WithMany("financialAids")
                        .HasForeignKey("PatientSSN")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("organization");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.MedicalInfo", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Patient", "Patient")
                        .WithMany("MedicalInfo")
                        .HasForeignKey("PatientSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbleEaseDomain.Entities.Relative", "Relative")
                        .WithMany("medicalInfo")
                        .HasForeignKey("RelativeSSN")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Patient");

                    b.Navigation("Relative");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.PatientDisability", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Disability", "disability")
                        .WithMany("patientDisabilities")
                        .HasForeignKey("DisabilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbleEaseDomain.Entities.Patient", "patient")
                        .WithMany("patientDisabilities")
                        .HasForeignKey("PatientSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("disability");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.PatientWorksAtOrganization", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Organization", "organization")
                        .WithMany("patientWorksAts")
                        .HasForeignKey("OrganizationSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbleEaseDomain.Entities.Patient", "patient")
                        .WithOne("worksAt")
                        .HasForeignKey("AbleEaseDomain.Entities.PatientWorksAtOrganization", "PatientSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Payment", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.FinancialAid", "financialAid")
                        .WithOne("payment")
                        .HasForeignKey("AbleEaseDomain.Entities.Payment", "FinancialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AbleEaseDomain.Entities.Patient", "patient")
                        .WithMany("payments")
                        .HasForeignKey("PatientSSN")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("financialAid");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.PhysicalTherapy", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.PhysiotherapyCenter", "center")
                        .WithMany()
                        .HasForeignKey("CenterID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AbleEaseDomain.Entities.Patient", "patient")
                        .WithMany("Therapies")
                        .HasForeignKey("PatientSSN")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("center");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Program", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Organization", "organization")
                        .WithMany("Programs")
                        .HasForeignKey("OrganizationSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.ReceivedMessages", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceivedSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Report", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Caregiver", "caregiver")
                        .WithMany("reports")
                        .HasForeignKey("CaregiverSSN")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AbleEaseDomain.Entities.Patient", "patient")
                        .WithMany("reports")
                        .HasForeignKey("PatientSSN")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AbleEaseDomain.Entities.Program", "program")
                        .WithMany("reports")
                        .HasForeignKey("ProgramOrganizationSSN", "ProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("caregiver");

                    b.Navigation("patient");

                    b.Navigation("program");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.SentMessages", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.User", "sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sender");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AbleEaseInfrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AbleEaseInfrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbleEaseInfrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AbleEaseInfrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Caregiver", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Organization", "organization")
                        .WithMany("caregivers")
                        .HasForeignKey("OrganizationSSN")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AbleEaseDomain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("AbleEaseDomain.Entities.Caregiver", "SSN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Organization", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("AbleEaseDomain.Entities.Organization", "SSN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Patient", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.Caregiver", "Caregiver")
                        .WithMany("patients")
                        .HasForeignKey("CaregiverSSN")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AbleEaseDomain.Entities.Relative", "Relative")
                        .WithOne("Patient")
                        .HasForeignKey("AbleEaseDomain.Entities.Patient", "RelativeSSN")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AbleEaseDomain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("AbleEaseDomain.Entities.Patient", "SSN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AbleEaseDomain.Entities.Program", "Program")
                        .WithMany("patients")
                        .HasForeignKey("ProgramOrganizationSSN", "ProgramId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Caregiver");

                    b.Navigation("Program");

                    b.Navigation("Relative");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Relative", b =>
                {
                    b.HasOne("AbleEaseDomain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("AbleEaseDomain.Entities.Relative", "SSN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Assessment", b =>
                {
                    b.Navigation("assessmentPatients");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Disability", b =>
                {
                    b.Navigation("patientDisabilities");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.FinancialAid", b =>
                {
                    b.Navigation("payment");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Program", b =>
                {
                    b.Navigation("Assessment");

                    b.Navigation("patients");

                    b.Navigation("reports");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.User", b =>
                {
                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Caregiver", b =>
                {
                    b.Navigation("patients");

                    b.Navigation("reports");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Organization", b =>
                {
                    b.Navigation("Programs");

                    b.Navigation("caregivers");

                    b.Navigation("financialAids");

                    b.Navigation("patientWorksAts");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Patient", b =>
                {
                    b.Navigation("MedicalInfo");

                    b.Navigation("Therapies");

                    b.Navigation("assessmentPatients");

                    b.Navigation("financialAids");

                    b.Navigation("patientDisabilities");

                    b.Navigation("payments");

                    b.Navigation("reports");

                    b.Navigation("worksAt");
                });

            modelBuilder.Entity("AbleEaseDomain.Entities.Relative", b =>
                {
                    b.Navigation("Patient");

                    b.Navigation("medicalInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
